// ─── Tour step definitions ────────────────────────────────────────────────────
// Kept in a separate file so App.jsx can import TOUR_STEPS synchronously
// for step-count logic without blocking the lazy load of GuidedTour.jsx itself.
export const TOUR_STEPS = [
  {
    title: 'Welcome to RentHack',
    body: 'This tool helps you underwrite 2–4 unit multifamily properties from first look to closing. Let\'s walk through the app together.',
    icon: '🏠',
    page: 'center',
  },
  {
    title: 'Your Deal Portfolio',
    body: 'This is your command center. Every deal you\'re analyzing lives here — filter by status, sort by returns, and spot your best opportunities.',
    target: 'portfolio-list',
    page: 'portfolio',
    placement: 'bottom',
  },
  {
    title: 'Create a New Deal',
    body: 'Click here to add a new deal. Each deal gets its own assumptions, projections, and analysis.',
    target: 'add-deal',
    page: 'portfolio',
    placement: 'bottom',
  },
  {
    title: 'Deal Summary',
    body: 'Your at-a-glance dashboard. See key metrics like CoC return, cap rate, IRR, equity multiple, and monthly cash flow — all calculated from your inputs.',
    target: 'tab-content',
    page: 'deal',
    tab: 0,
    placement: 'top',
  },
  {
    title: 'Assumptions',
    body: 'Enter the purchase price, financing terms, unit rents, and operating expenses here. Paste a Zillow or Redfin URL to auto-fill property data with Rentcast.',
    target: 'tab-content',
    page: 'deal',
    tab: 1,
    placement: 'top',
  },
  {
    title: 'Advanced Scenarios',
    body: 'Model owner-occupied cash flow (live in one unit), refinance scenarios (cash-out refi at year N), and value-add plays (renovate units to lift rents).',
    target: 'advanced-features',
    page: 'deal',
    tab: 1,
    placement: 'top',
  },
  {
    title: 'Cash Flow Projections',
    body: '10-year projections showing income growth, expenses, debt service, cash flow, and equity accumulation year by year.',
    target: 'tab-content',
    page: 'deal',
    tab: 2,
    placement: 'top',
  },
  {
    title: 'Rent Comps',
    body: 'Compare your rents against market data. Paste a listing URL to pull nearby rental comps and see how your assumptions stack up.',
    target: 'tab-content',
    page: 'deal',
    tab: 3,
    placement: 'top',
  },
  {
    title: 'Showing Notes',
    body: 'Log your property visit — record condition, first impressions, and rehab estimates. Tag photos to specific areas of the property.',
    target: 'tab-content',
    page: 'deal',
    tab: 4,
    placement: 'top',
  },
  {
    title: 'Red Flags',
    body: 'Automatic risk checks flag issues with DSCR, cap rate, and expense ratios against your thresholds. Add manual flags for anything you spot on-site.',
    target: 'tab-content',
    page: 'deal',
    tab: 5,
    placement: 'top',
  },
  {
    title: 'Sensitivity Analysis',
    body: 'See how your returns shift when rent, vacancy, purchase price, interest rate, or appreciation change. Stress-test the deal before you commit.',
    target: 'tab-content',
    page: 'deal',
    tab: 6,
    placement: 'top',
  },
  {
    title: "You're ready to analyze deals!",
    body: 'Start by clicking + Add to create your first deal, or paste a listing URL directly into the Property Lookup panel. Your data syncs automatically across devices.',
    icon: '🚀',
    page: 'center',
  },
];
